export type AgentType = "local" | "claude";

export interface Agent {
  /** Folder/slug name under data/agents. */
  id: string;
  name: string;
  description: string;
  /** local = configured provider; claude = Claude Code MCP harness (for dev tasks). */
  type: AgentType;
  systemPrompt: string;
  /** Tool ids this sub-agent may use (local agents). Empty = all default tools. */
  tools?: string[];
  /** Skill ids this agent may load. Unset/empty = all skills. */
  skills?: string[];
  /** MCP server names/endpoints this agent may use. Unset/empty = all. */
  mcp?: string[];
  /** Knowledge base ids this agent may query (038-knowledge-base). Unset/empty
   *  = all KBs the Knowledge Base item knows about; a non-empty list scopes
   *  the agent's kb_search/kb_retrieve to only these ids. */
  kbs?: string[];
  /** Tool ids this agent should treat as deferred (hidden from its initial
   *  context, discoverable via find_tools). This is the ONLY source of
   *  deferred-ness — there is no registry-wide default. Unset/empty ⇒ nothing
   *  is deferred for this agent (every allowed tool is visible from the start). */
  deferredTools?: string[];
  /** When true (default), prepend the shared default prompt (edited in Settings
   *  → Agents → Default Agent) to the agent's own system prompt. When false, only
   *  the agent's own systemPrompt is used. */
  useDefaultPrompt?: boolean;
  model?: string;
  /** For claude agents: the harness Agent subagent_type. Generated by the
   *  assistant when creating the agent; defaults to the agent id. */
  subagentType?: string;
  /** Ephemeral agents are not persisted; they live only for one task. */
  ephemeral?: boolean;
  /** 045 FR-002: which root contributed this agent ("This deployment",
   *  "BrowserOS", or a pack's label). The picker groups by it, so two packs'
   *  similarly-named agents stay distinguishable. Derived at discovery time,
   *  never stored in AGENT.md. */
  sourceRoot?: string;
  /** 045: the method pack that contributed it, when one did. Used to fail a
   *  delegation NAMING the pack once it is uninstalled (FR-016), rather than
   *  reporting a bare "unknown agent". */
  packId?: string;
}

/** Token usage for a whole sub-agent RUN, summed across its model turns
 *  (031-self-healing ADR-5). Framework-free and optional: a provider or harness
 *  that reports nothing leaves it `undefined`, which callers must read as
 *  "unknown", never as zero. `estimated` marks a value derived from a fallback
 *  heuristic rather than a provider report. */
export interface AgentRunUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
  estimated?: boolean;
}

/** Why a run stopped (031-self-healing scope-add, M1/ADR-13). The local
 *  headless runner surfaces the agent loop's own end reason here; the CLI path
 *  has no step loop, so it reports only `completed`/`error` and never
 *  `max_steps`. It exists because "ended cleanly" and "ran out of steps" are
 *  different facts, and a consumer (self-heal's stuck detection, FR-033(b))
 *  cannot tell them apart from `error` alone. */
export type AgentRunEndedReason = "completed" | "cancelled" | "error" | "max_steps";

export interface AgentRunResult {
  agent: string;
  type: AgentType;
  task: string;
  output: string;
  steps: number;
  toolCalls: { tool: string; input: unknown }[];
  error?: string;
  /** What this run cost, when the provider/harness reported it. */
  usage?: AgentRunUsage;
  /** This run's id — the same one the leading `run_started` event carries, the
   *  transcript file is named after, and `abortHeadlessRun` takes. Generated by
   *  each runner (before any early return), so it is always present. */
  runId: string;
  /** How the run ended. See AgentRunEndedReason. */
  endedReason?: AgentRunEndedReason;
  /** True when the run was terminated by `abortHeadlessRun` (ADR-11), so a
   *  caller that did NOT initiate the abort can still detect one. */
  aborted?: boolean;
}

/** Events a (headless) sub-agent run forwards to its caller via `runSubAgent`'s
 *  `onEvent`. The first member is the LEGACY tool-call shape (`{ tool, input }`,
 *  unchanged, emitted by both the local and Claude runners). ADR-13 (Workflow
 *  Manager service-tools) adds the enriched members so a consuming service can
 *  log the full agent-execution stream (tool results with ok/error, reasoning,
 *  and the final text) without round-trip reconstruction. The enriched members
 *  are only emitted by the local headless path (`runLocalHeadless`).
 *
 *  031-self-healing's scope-add adds `run_started`, which BOTH runners emit as
 *  the FIRST event of a run: it is how a caller learns the runId while the run
 *  is still in flight, which is what makes Stop (FR-032/FR-034) and case→run
 *  linkage (ADR-12) possible at all — the returned result comes far too late for
 *  a fire-and-forget run. */
export type SubAgentEvent =
  | { tool: string; input: unknown }
  | { type: "run_started"; runId: string; agentId: string; startedAt: string; parentRunId?: string }
  | { type: "tool_result"; name: string; result: string; ok: boolean }
  | { type: "reasoning_delta"; delta: string }
  | { type: "final_text"; text: string };
