export type AgentType = "local" | "claude";

export interface Agent {
  /** Folder/slug name under data/agents. */
  id: string;
  name: string;
  description: string;
  /** local = configured provider; claude = Claude Code MCP harness (for dev tasks). */
  type: AgentType;
  systemPrompt: string;
  /** Tool ids this sub-agent may use (local agents). Empty = all default tools. */
  tools?: string[];
  /** Skill ids this agent may load. Unset/empty = all skills. */
  skills?: string[];
  /** MCP server names/endpoints this agent may use. Unset/empty = all. */
  mcp?: string[];
  /** Tool ids this agent should treat as deferred (hidden from its initial
   *  context, discoverable via find_tools). Additive to the registry default:
   *  the effective deferred set for a run is `registryDefaults ∪ deferredTools`.
   *  A tool listed here cannot be re-exposed by omission — the registry's own
   *  `deferred: true` still applies. Unset/empty ⇒ use registry defaults only. */
  deferredTools?: string[];
  /** When true (default), prepend the shared default prompt (edited in Settings
   *  → Agents → Default Agent) to the agent's own system prompt. When false, only
   *  the agent's own systemPrompt is used. */
  useDefaultPrompt?: boolean;
  model?: string;
  /** For claude agents: the harness Agent subagent_type. Generated by the
   *  assistant when creating the agent; defaults to the agent id. */
  subagentType?: string;
  /** Ephemeral agents are not persisted; they live only for one task. */
  ephemeral?: boolean;
}

export interface AgentRunResult {
  agent: string;
  type: AgentType;
  task: string;
  output: string;
  steps: number;
  toolCalls: { tool: string; input: unknown }[];
  error?: string;
}
