// Build-time discovery of BrowserOS built-in apps.
//
// Built-in apps live as self-describing folders under src/apps/<id>/, mirroring
// how user apps live under the GitFS apps repo: each folder has a `manifest.ts`
// (app metadata) and an `index.tsx` (the React entry component, default export).
//
// Unlike user apps — which are iframes discovered at runtime with readdir — a
// built-in app is a React component compiled into the BOS bundle, so it must be
// reachable via static imports. We can't readdir a component into a running
// bundle, and Turbopack has no require.context/import.meta.glob, so we generate
// the static import graph here instead of hand-maintaining a central registry.
//
// Output (gitignored, regenerated on predev/prebuild):
//   src/apps/_manifests.generated.ts   — BUILTIN_APPS: AppManifest[]
//   src/apps/_components.generated.ts   — BUILTIN_COMPONENTS: Record<id, AppComponent>
//
// Convention: the folder name IS the app id (manifest.id must match it), exactly
// like user apps. Add an app by dropping a folder here — no registry edit, no
// merge conflict.

import { readdirSync, existsSync, writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const APPS_DIR = join(ROOT, "src", "apps");

/** A safe TS identifier derived from an app id (folder name). */
function ident(id) {
  const s = id.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(s) ? `_${s}` : s;
}

function discover() {
  return readdirSync(APPS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((id) => existsSync(join(APPS_DIR, id, "manifest.ts")) && existsSync(join(APPS_DIR, id, "index.tsx")))
    .sort();
}

const HEADER =
  "// AUTO-GENERATED by tools/gen-apps.mjs — do not edit by hand.\n" +
  "// Regenerated on `npm run dev` / `npm run build` (predev/prebuild) and by\n" +
  "// `npm run gen:apps`. Lists the built-in apps discovered under src/apps/<id>/.\n\n";

function manifestsModule(ids) {
  const imports = ids.map((id) => `import manifest_${ident(id)} from "./${id}/manifest";`).join("\n");
  const list = ids.map((id) => `  manifest_${ident(id)},`).join("\n");
  return (
    HEADER +
    `import type { AppManifest } from "@/os/types";\n` +
    (imports ? imports + "\n" : "") +
    `\nexport const BUILTIN_APPS: AppManifest[] = [\n${list}${list ? "\n" : ""}];\n`
  );
}

function componentsModule(ids) {
  const imports = ids.map((id) => `import app_${ident(id)} from "./${id}";`).join("\n");
  const entries = ids.map((id) => `  ${JSON.stringify(id)}: app_${ident(id)},`).join("\n");
  return (
    HEADER +
    `import type { AppComponent } from "@/components/apps/types";\n` +
    (imports ? imports + "\n" : "") +
    `\nexport const BUILTIN_COMPONENTS: Record<string, AppComponent> = {\n${entries}${entries ? "\n" : ""}};\n`
  );
}

/** Only write when content changed, to avoid needless dev-server recompiles. */
function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;
  writeFileSync(path, content);
  return true;
}

export function generateApps() {
  const ids = discover();
  writeIfChanged(join(APPS_DIR, "_manifests.generated.ts"), manifestsModule(ids));
  writeIfChanged(join(APPS_DIR, "_components.generated.ts"), componentsModule(ids));
  return ids;
}

const ids = generateApps();
console.log(`gen-apps: ${ids.length} built-in app(s): ${ids.join(", ") || "(none)"}`);
