// 051 T023 — is this descriptor structurally sound? (FR-017)
//
// Runs before every write in `authoring.ts`, so an edit cannot leave a workflow
// in a state that throws later, for every unit, somewhere else.
//
// PURE and free of I/O, like `graph.ts`: a descriptor in, problems out. The
// canvas, the API route and `methods_edit` must agree about what "valid" means,
// and one function is the only way they do (SC-011).
//
// WHAT THIS DELIBERATELY DOES NOT CHECK
//
// Two plausible rules are absent, and both were measured against the packs
// before being ruled out — they would flag BOS's own default method as broken:
//
//   "every artifact is generated by some phase"
//       spec-kit ships THREE that are not: research.md, data-model.md and
//       quickstart.md. `generates` is optional in the schema and those artifacts
//       are written by hand.
//
//   "every phase is reachable from some other phase"
//       spec-kit declares ZERO gates, so under this rule all twelve phases are
//       unreachable. Isolation is real and worth SHOWING — `graph.ts` reports it
//       with a reason — but it is a diagnostic, not a defect.
//
// The line between the two lists is whether the condition makes the pipeline
// FAIL. Everything below either throws in `evaluate.ts` or silently drops
// something the author wrote; nothing below is a matter of taste.

import type { MethodDescriptor, Predicate } from "./types";

export type ProblemCode =
  /** `phases[].requires` names something that is not a phase. `evaluate.ts`
   *  throws on it — "referenced but not declared" — for every unit. */
  | "unknown-phase"
  /** A `dependsOn` predicate names something that is not a phase. Same throw,
   *  reached through the rule clauses instead of the edge list. */
  | "unknown-depends-on"
  /** Two phases share an id. `evaluate.ts` builds a Map keyed by id, so the
   *  second silently wins and the first becomes unreachable data. */
  | "duplicate-phase"
  /** A dependency cycle. `evaluate.ts` detects it at runtime and throws. */
  | "cycle"
  /** `artifacts[].generates` names something that is not a phase. No throw —
   *  which is worse: `graph.ts` drops the edge and the artifact quietly stops
   *  appearing to have a producer. */
  | "unknown-generates"
  /** `artifacts[].requires` names something that is not an artifact. Same
   *  silent drop. */
  | "unknown-artifact"
  /** No phases at all. `registerMethod` refuses this, so an edit that produced
   *  it would be written and then rejected on reload — an unloadable workflow. */
  | "no-phases";

export interface ValidationProblem {
  code: ProblemCode;
  /** Written for whoever has to fix it: what is wrong, where, and what it will
   *  do if left. A code alone sends someone to the source of the validator. */
  message: string;
  phase?: string;
  artifact?: string;
}

/**
 * Every phase a phase's RULES depend on, via `dependsOn`.
 *
 * A structural walk, for the same reason `graph.ts` walks rather than switching:
 * `dependsOn` can be nested inside `all`, `any`, `not` and `set`, and a switch
 * over predicate kinds silently misses whichever nesting it was not taught.
 */
function dependsOnTargets(rules: unknown, onMalformed: (what: string) => void): string[] {
  const out: string[] = [];
  const visit = (node: unknown): void => {
    if (Array.isArray(node)) {
      for (const item of node) visit(item);
      return;
    }
    if (typeof node !== "object" || node === null) return;
    const rec = node as Record<string, unknown>;
    if ((rec as Predicate & { kind?: string }).kind === "dependsOn") {
      if (typeof rec.phase === "string") out.push(rec.phase);
      else onMalformed("a `dependsOn` with no phase name");
    }
    for (const v of Object.values(rec)) visit(v);
  };
  visit(rules);
  return out;
}

/**
 * A cycle in the phase dependency graph, as the path that closes it.
 *
 * Over GATES **and** `dependsOn`, not gates alone. The task that specified this
 * said gates; reading `evaluate.ts` says otherwise — `resolve()` recurses through
 * `phases[].requires` AND through every `dependsOn` predicate, and its
 * `inFlight` guard throws on either. Checking only gates would pass a descriptor
 * that throws for every unit in the store the moment it is bound.
 */
function findCycle(edges: Map<string, Set<string>>): string[] | null {
  const colour = new Map<string, 0 | 1 | 2>(); // 0 unseen, 1 on the stack, 2 done
  const stack: string[] = [];

  const walk = (id: string): string[] | null => {
    if (colour.get(id) === 2) return null;
    if (colour.get(id) === 1) return [...stack.slice(stack.indexOf(id)), id];
    colour.set(id, 1);
    stack.push(id);
    for (const next of edges.get(id) ?? []) {
      const found = walk(next);
      if (found) return found;
    }
    stack.pop();
    colour.set(id, 2);
    return null;
  };

  for (const id of edges.keys()) {
    const found = walk(id);
    if (found) return found;
  }
  return null;
}

/** Problems with a descriptor, in the order someone would fix them. Empty means
 *  sound — never "probably fine". */
export function validateDescriptor(d: MethodDescriptor): ValidationProblem[] {
  const problems: ValidationProblem[] = [];
  const phases = d.phases ?? [];

  if (phases.length === 0) {
    problems.push({
      code: "no-phases",
      message: "A workflow needs at least one phase. Saving this would produce a workflow that cannot be loaded again — registerMethod refuses a descriptor with no phases.",
    });
    return problems;
  }

  const seen = new Set<string>();
  for (const p of phases) {
    if (seen.has(p.id)) {
      problems.push({
        code: "duplicate-phase",
        phase: p.id,
        message: `Two phases are both called "${p.id}". Phases are looked up by id, so the second would win and the first would never be evaluated.`,
      });
    }
    seen.add(p.id);
  }

  // Dependency edges, from both sources that `evaluate.ts` recurses through.
  const deps = new Map<string, Set<string>>();
  for (const p of phases) deps.set(p.id, new Set());

  for (const p of phases) {
    for (const req of p.requires ?? []) {
      if (!seen.has(req)) {
        problems.push({
          code: "unknown-phase",
          phase: p.id,
          message: `"${p.label || p.id}" requires "${req}", which is not a phase in this workflow. Evaluating any unit would fail with "referenced but not declared".`,
        });
        continue;
      }
      deps.get(p.id)?.add(req);
    }

    for (const target of dependsOnTargets(p.rules, (what) => {
      problems.push({ code: "unknown-depends-on", phase: p.id, message: `"${p.id}" has ${what}.` });
    })) {
      if (!seen.has(target)) {
        problems.push({
          code: "unknown-depends-on",
          phase: p.id,
          message: `A rule on "${p.label || p.id}" depends on phase "${target}", which is not in this workflow. Evaluating any unit would fail.`,
        });
        continue;
      }
      deps.get(p.id)?.add(target);
    }
  }

  const cycle = findCycle(deps);
  if (cycle) {
    problems.push({
      code: "cycle",
      phase: cycle[0],
      message: `These phases depend on each other in a loop: ${cycle.join(" -> ")}. Evaluating any unit would fail with a cyclic dependency.`,
    });
  }

  const artifactIds = new Set(d.artifacts?.map((a) => a.id) ?? []);
  for (const a of d.artifacts ?? []) {
    if (a.generates && !seen.has(a.generates)) {
      problems.push({
        code: "unknown-generates",
        artifact: a.id,
        message: `"${a.id}" says it is generated by "${a.generates}", which is not a phase in this workflow. Nothing throws — the link is just dropped, so the artifact silently appears to have no producer.`,
      });
    }
    for (const req of a.requires ?? []) {
      if (!artifactIds.has(req)) {
        problems.push({
          code: "unknown-artifact",
          artifact: a.id,
          message: `"${a.id}" requires artifact "${req}", which this workflow does not declare. The dependency is silently ignored.`,
        });
      }
    }
  }

  return problems;
}

/** One line per problem, for an agent or a log. The UI renders the structured
 *  list; this is for the places that only have a string. */
export function describeProblems(problems: ValidationProblem[]): string {
  return problems.map((p) => `- ${p.message}`).join("\n");
}
